version: '3'

services:
    migration:
      build: .
      command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate"
      volumes:
        - .:/code
    django:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - migration


